version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
  django:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    depends_on:
      - psql
  react:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src